PRODUCT_VERSION_MAJOR = 21
PRODUCT_VERSION_MINOR = 0

ARES_VERSION = v14.0
ARES_EDITION := GAPPS
ARES_BUILD_DATETIME := $(shell date +%s)
ARES_BUILD_DATE := $(shell date -d @$(ARES_BUILD_DATETIME) +"%Y%m%d-%H%M%S")

# Internal version
LINEAGE_VERSION := AresOS-$(ARES_VERSION)-$(ARES_EDITION)-$(ARES_BUILD_DATE)

# Display version
LINEAGE_DISPLAY_VERSION := AresOS-$(ARES_VERSION)-$(ARES_EDITION)-$(ARES_BUILD_DATE)
